$ErrorActionPreference='Stop'
Import-Module (Join-Path $PSScriptRoot 'hosted-present-root-support.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'hosted-capability-verdict.psm1') -Force
function Clone($Value){ConvertFrom-Json (ConvertTo-Json $Value -Depth 64) -AsHashtable}
function New-Golden {
 $run='a'*32;$sha='b'*40;$sid='S-1-5-21-1-2-3-1001';$thumb='C'*40;$subject="CN=Ticket569-Root-Prompt-$run"
 $importer=@{pid=11;creationFileTimeUtc=12;sid=$sid;sessionId=7}
 $removalIdentity=@{pid=41;creationFileTimeUtc=42;role='root-remove'}
 $remove=@{schema='ticket569-currentuser-root-import-v1';runId=$run;sid=$sid;sessionId=7;subject=$subject;thumbprint=$thumb;passed=$true;removedOwned=$true;removedObserved=$true;processId=41;processCreationFileTimeUtc=42}
 $mutation=@{intent=@{operation='recovery-remove-exact-owned-currentuser-root-certificate';resourceIdentity=@{thumbprint=$thumb};precondition=@{exactSubjectMatch=$true;uniqueThumbprintMatch=$true;preabsenceSequence=2;importAttemptSequence=3};processIdentity=$removalIdentity};observation=@{result='completed';observed=@{absent=$true}}}
 $e=@{testFault='present-root-recovery';runId=$run;sourceSHA=$sha;intercept=@{eligible=$true;waited=$true;exitCode=137;importer=$importer;resource=@{thumbprint=$thumb;subject=$subject};preabsenceSequence=2;importSequence=3};barrier=@{accepted=$true;workerWaited=$true;workerExit=137;workerJobEmpty=$true;proof=@{context=@{profilePath='C:\Users\fixture'};admission=@{allowed=$true;counter=1000;workDeadline=2000;cleanupDeadline=3000}}};recovery=@{failed=$false;rootStatus='verified';rootSubjectRemaining=$false;credentialFinalCredReadError=1168;sessionLeftActiveForSupervisorLogoff=$true;removedRootThumbprints=@($thumb);runId=$run;sourceSHA=$sha;sid=$sid;sessionId=7;profilePath='C:\Users\fixture';sessionHostHealthBefore=@{healthy=$true};sessionHostHealthAfter=@{healthy=$true}};removeResult=$remove;removalExit=@{processIdentity=$removalIdentity;observed=@{waitedHandle=$true;identityMatched=$true;exitCode=0}};launcherExitCode=0;recoveryJobEmpty=$true;launcher=@{pid=21;creationFileTimeUtc=22;scriptSHA256=('d'*64);workerScriptSHA256=('e'*64)};launcherAncestry=@{launcher=@{pid=21;scriptSHA256=('d'*64)};workerScriptSHA256=('e'*64);suspendedChildValidated=$true;gateReleased=$true;child=@{sid=$sid;sessionId=7;creationFileTimeUtc=32}};removalConsent=@{status='observed-and-answered';promptClosed=$true;observation=@{pid=51;windowId=52;affirmativeElementToken='adapted-token'}};counterFrequency=1;recoveryCompletedCounter=2200;recoveryCutoff=2500;cleanupDeadline=3000}
 $completion=@{testFault='present-root-recovery';runId=$run;sourceSHA=$sha;failure=$true;failureLatched=$true;cleanupStatus='unverified';supervisorVerdict='cleanup-failed';localFinalWriteProven=$true;supervisorFinalized=$true;ledgerReplayValid=$true;ledgerPendingMutationCount=0;workerExit=137;workerTerminationProven=$true;ownerCleanupComplete=$true;recoveryRequired=$true;recoveryCompleted=$true;activeProcesses=0;ownerActiveProcessesFinal=0;recoveryActiveProcessesFinal=0;presentRootExercise=@{recoveryEvidence=$e;cleanupCompletedCounter=2600;ownedCleanup=@{profileRemoved=$true;userRemoved=$true}}}
 $events=@(@{phase='process';operation='supervisor-started';resourceIdentity=@{testFault='present-root-recovery'}},@{operation='same-session-recovery-completed-before-j-plus-24';resourceIdentity=@{sensitiveContextProven=$true;ownedCleanup=@{profileRemoved=$true;userRemoved=$true}}})
 $mutations=@($mutation)
 foreach($op in @('remove-exact-run-localmachine-prompt-certificate','remove-empty-owned-hosted-runtime-root')){$mutations+=@{intent=@{operation=$op};observation=@{result='completed';observed=@{absent=$true}}}}
 $identity=@{testFault='present-root-recovery';runId=$run;sourceSHA=$sha}
 $binding=@{runId=$run;sourceSHA=$sha;leaseId='synthetic-lease';resources=@{}}
 $absence=@{schema='ticket569-present-root-independent-absence-v1';runId=$run;sourceSHA=$sha;sid=$sid;sessionId=7;verifier='distinct-adapter';executor='adapter-executor';leaseId='synthetic-lease';resources=@{}}
 foreach($name in @('account','rdpMembership','profileRecord','profileDirectory','profileHive','userSession','exportedCer','localMachinePromptCertificate','probeTasks','runtimeDirectory','participantProcesses','jobs','azureResources','brokerCredentials','sshKey','tunnel','rdpConnection')){$expected=@{name="synthetic-owned-$name"};$binding.resources[$name]=$expected;$absence.resources[$name]=@{absent=$true;resourceIdentity=$expected;rawEvidenceSHA256=('f'*64)}}
 @{Identity=$identity;Completion=$completion;Replay=@{valid=$true;pending=@();events=$events;mutations=$mutations};IndependentAbsence=$absence;ResourceBinding=$binding;SupervisorExitCode=2}
}
$golden=New-Golden
if(!(Test-HostedPresentRootRecoverySupport @golden).qualifiedSupportingObserved){throw ('Complete qualified adapter refused '+(ConvertTo-Json (Test-HostedPresentRootRecoverySupport @golden) -Depth 10))}
function Refuse($InputCase,[string]$Name){$v=Test-HostedPresentRootRecoverySupport @InputCase;if($v.qualifiedSupportingObserved -or $v.acceptanceCredit -or $v.historicalCauseCredit){throw "Supporting fault passed $Name"};Write-Output "PRESENT_ROOT_SUPPORT_ADAPTER_REFUSED $Name"}
foreach($path in @('failure','failureLatched','localFinalWriteProven','supervisorFinalized','ledgerReplayValid','workerTerminationProven','ownerCleanupComplete','recoveryRequired','recoveryCompleted')){
 foreach($value in @($false,'true',@{truthy=$true},$null)){$bad=Clone $golden;$bad.Completion[$path]=$value;Refuse $bad "completion-$path-$($value -is [bool])"}
}
foreach($path in @('eligible','waited')){foreach($value in @($false,'true',@{truthy=$true},$null)){$bad=Clone $golden;$bad.Completion.presentRootExercise.recoveryEvidence.intercept[$path]=$value;Refuse $bad "intercept-$path"}}
foreach($path in @('accepted','workerWaited','workerJobEmpty')){foreach($value in @($false,'true',@{truthy=$true},$null)){$bad=Clone $golden;$bad.Completion.presentRootExercise.recoveryEvidence.barrier[$path]=$value;Refuse $bad "barrier-$path"}}
foreach($path in @('passed','removedOwned','removedObserved')){foreach($value in @($false,'true',@{truthy=$true},$null)){$bad=Clone $golden;$bad.Completion.presentRootExercise.recoveryEvidence.removeResult[$path]=$value;Refuse $bad "remove-$path"}}
foreach($fault in @('identity-none','completion-none','missing-binding','false-overall-success','zero-exit','missing-exit','wrong-run','wrong-source','pending','invalid-ledger','ledger-none','already-absent','remove-subject','remove-thumb','remove-session','remove-nonzero','unwaited','timeout','health-before','health-after','readback','readback-malformed','credentials','ancestry','removal-cua','deadline-recovery','deadline-cleanup','cleanup-profile','cleanup-event','cleanup-cert','cleanup-runtime','independent-missing','same-verifier','wrong-lease','wrong-resource','wrong-evidence-hash')){
 $bad=Clone $golden;$e=$bad.Completion.presentRootExercise.recoveryEvidence
 switch($fault){
  identity-none {$bad.Identity.testFault='none'} completion-none {$bad.Completion.testFault='none'} missing-binding {$bad.Identity.Remove('testFault')} false-overall-success {$bad.Completion.supervisorVerdict='feasible-observed'} zero-exit {$bad.SupervisorExitCode=0} missing-exit {$bad.Completion.Remove('workerExit')} wrong-run {$bad.Identity.runId='d'*32} wrong-source {$e.sourceSHA='d'*40} pending {$bad.Replay.pending=@(@{operation='pending'})} invalid-ledger {$bad.Replay.valid=$false} ledger-none {$bad.Replay.events[0].resourceIdentity.testFault='none'}
  already-absent {$bad.Replay.mutations=@($bad.Replay.mutations|Where-Object {$_.intent.operation -cne 'recovery-remove-exact-owned-currentuser-root-certificate'});$e.recovery.removedRootThumbprints=@()} remove-subject {$e.removeResult.subject='wrong'} remove-thumb {$e.removeResult.thumbprint='D'*40} remove-session {$e.removeResult.sessionId=8} remove-nonzero {$e.removalExit.observed.exitCode=7} unwaited {$e.removalExit.observed.waitedHandle=$false} timeout {$e.launcherExitCode=2} health-before {$e.recovery.sessionHostHealthBefore.healthy=$false} health-after {$e.recovery.sessionHostHealthAfter.healthy='true'} readback {$e.recovery.rootSubjectRemaining=$true} readback-malformed {$e.recovery.rootSubjectRemaining='false'} credentials {$e.recovery.credentialFinalCredReadError=0} ancestry {$e.launcherAncestry.child.creationFileTimeUtc=$null} removal-cua {$e.removalConsent.promptClosed=$false} deadline-recovery {$e.recoveryCompletedCounter=$e.recoveryCutoff} deadline-cleanup {$bad.Completion.presentRootExercise.cleanupCompletedCounter=$e.cleanupDeadline} cleanup-profile {$bad.Completion.presentRootExercise.ownedCleanup.profileRemoved='true'} cleanup-event {$bad.Replay.events=@($bad.Replay.events[0])} cleanup-cert {$bad.Replay.mutations=@($bad.Replay.mutations|Where-Object {$_.intent.operation -cne 'remove-exact-run-localmachine-prompt-certificate'})} cleanup-runtime {$bad.Replay.mutations=@($bad.Replay.mutations|Where-Object {$_.intent.operation -cne 'remove-empty-owned-hosted-runtime-root'})} independent-missing {$bad.IndependentAbsence.resources.Remove('account')} same-verifier {$bad.IndependentAbsence.verifier=$bad.IndependentAbsence.executor} wrong-lease {$bad.IndependentAbsence.leaseId='different'} wrong-resource {$bad.IndependentAbsence.resources.account.resourceIdentity=@{name='unrelated'}} wrong-evidence-hash {$bad.IndependentAbsence.resources.account.rawEvidenceSHA256='bad'}
 }
 Refuse $bad $fault
}
foreach($name in $golden.IndependentAbsence.resources.Keys){foreach($value in @($false,'true',@{truthy=$true},$null)){$bad=Clone $golden;$bad.IndependentAbsence.resources[$name].absent=$value;Refuse $bad "absence-$name"}}
$normal=@{TestFault='none';WorkerVerdict='feasible-observed';CleanupStatus='complete';TerminationProven=$true;WorkerIdentityProven=$true;FailureLatched=$false;LocalFinalWriteProven=$true;RecoveryContextProven=$true}
foreach($mode in @('before-runtime-intent','after-user-create','present-root-recovery','NONE')){$bad=$normal.Clone();$bad.TestFault=$mode;if((Resolve-HostedCapabilitySupervisorVerdict @bad).verdict -ceq 'feasible-observed'){throw 'Non-none qualified exercise became capability feasible'}}
$bad=$normal.Clone();$bad.TestFault='malformed';$refused=$false;try{$null=Resolve-HostedCapabilitySupervisorVerdict @bad}catch{$refused=$true};if(!$refused){throw 'Malformed verdict TestFault accepted'}
# Binding metadata makes omission fail before the verdict producer can run.
$parameter=(Get-Command Resolve-HostedCapabilitySupervisorVerdict).Parameters.TestFault
if(!@($parameter.Attributes|Where-Object {$_ -is [Management.Automation.ParameterAttribute] -and $_.Mandatory}).Count){throw 'Missing TestFault no longer a mandatory binding failure'}
$supervisor=[IO.File]::ReadAllText((Join-Path $PSScriptRoot 'hosted-capability-supervisor.ps1'))
$watchdog=[IO.File]::ReadAllText((Join-Path $PSScriptRoot 'hosted-capability-watchdog.ps1'))
$workflow=[IO.File]::ReadAllText((Join-Path $PSScriptRoot '../../.github/workflows/hosted-capability.yml'))
if(!$supervisor.Contains("if(`$env:GITHUB_ACTIONS -eq 'true' -and `$TestFault -ceq 'present-root-recovery')") -or $workflow.Contains('-TestFault')){throw 'Fault exercise became workflow-accessible'}
if(!$watchdog.Contains("`$requiredCompletionFields=@('testFault'") -or !$watchdog.Contains("`$completion.testFault -cne 'none'")){throw 'Watchdog completion containment missing'}
Write-Output 'PRESENT_ROOT_SUPPORT_VALIDATOR_CONTAINMENT_FAULTS_PASSED;ALL_SUPPORT_INPUTS_SYNTHETIC_NATIVE_AND_INDEPENDENT_ABSENCE_UNRUN'
