// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mapi} from '../models';

export function GetQueue():Promise<Array<mapi.EmailWithId>>;

export function SetTrayError(arg1:string):Promise<void>;
