// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetQueue() {
  return window['go']['main']['App']['GetQueue']();
}

export function SetTrayError(arg1) {
  return window['go']['main']['App']['SetTrayError'](arg1);
}
