// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {mapi} from '../models';

export function GetAuthStatus():Promise<main.AuthStatus>;

export function GetQueue():Promise<Array<mapi.EmailWithId>>;

export function SetTrayError(arg1:string):Promise<void>;

export function SignIn():Promise<void>;

export function SignOut():Promise<void>;
