// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDraftForID(arg1) {
  return window['go']['main']['App']['CreateDraftForID'](arg1);
}

export function DismissEmail(arg1) {
  return window['go']['main']['App']['DismissEmail'](arg1);
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetMode() {
  return window['go']['main']['App']['GetMode']();
}

export function GetPausedState() {
  return window['go']['main']['App']['GetPausedState']();
}

export function GetQueue() {
  return window['go']['main']['App']['GetQueue']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function MakeAuthenticatedGmailCall(arg1, arg2) {
  return window['go']['main']['App']['MakeAuthenticatedGmailCall'](arg1, arg2);
}

export function PauseWatching() {
  return window['go']['main']['App']['PauseWatching']();
}

export function ResumeWatching() {
  return window['go']['main']['App']['ResumeWatching']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1);
}

export function SetPaused(arg1) {
  return window['go']['main']['App']['SetPaused'](arg1);
}

export function SetTrayError(arg1) {
  return window['go']['main']['App']['SetTrayError'](arg1);
}

export function SetTrayIdle(arg1) {
  return window['go']['main']['App']['SetTrayIdle'](arg1);
}

export function SignIn() {
  return window['go']['main']['App']['SignIn']();
}

export function SignOut() {
  return window['go']['main']['App']['SignOut']();
}
