// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetQueue() {
  return window['go']['main']['App']['GetQueue']();
}

export function SetTrayError(arg1) {
  return window['go']['main']['App']['SetTrayError'](arg1);
}

export function SignIn() {
  return window['go']['main']['App']['SignIn']();
}

export function SignOut() {
  return window['go']['main']['App']['SignOut']();
}
